def estrofe(arg):
    print(f'{arg} patinhos')
    print(f'Foram passear')
    print(f'Além das montanhas')
    print(f'Para brincar')
    print(f'A mamãe gritou')
    print(f'Quá, quá, quá, quá!')
    print(f'Mas só {arg-1} patinhos')
    print(f'Voltaram de lá')
    print("Agora só falta aprender a fazer loop!")